### ISSUE TITLE
Sound Assets - 1hour30min

### ISSUE THREAD

**Issue by Courtney-jade1997** [UoSGamesGroups/first-semester-l-4-5-group-5#44]
Find sound assets online for our game to create a medieval dungeon atmosphere. Only use sound effects which are free, ***do not*** use someone else's work. 

- Fire burning in the torches.
- creepy music
- water dripping 
- muffled voices of the guards
- unlocking doors 
- lever noise 
- creaking doors / floor boards 
- noise when taking over guard 

Good websites to look at to start:
incompitech

Think about our two emotions when choosing the music, we need the player to feel lost and alone.

**Comment by HenrySmith1498** [comment]
1 hour 30 minutes
