### ISSUE TITLE
Create different coloured versions of each guard - 3hour

### ISSUE THREAD

**Issue by Defunct-Account-02445** [UoSGamesGroups/first-semester-l-4-5-group-5#54]
Create different coloured versions of each guard (This will result in 18 versions in total). 

To recolour these you have been assigned 1 hour for each guard. 

- Dark red
- Dark purple
- Dark blue
- Terquoise
- Dark Orange
- Dark Brown

**Comment by HenrySmith1498** [comment]
3 hours
